### ISSUE TITLE
static analysis tools

### ISSUE THREAD

**Issue by posix4e** [hCaptcha/eth-kvstore#20]
- [x] Manticore
- [x] surya
- [ ] myrthrill
- [x] Slither

**Comment by posix4e** [comment]
It crashes
```
posix4e@localhost:~/src/eth-kvstore$ manticore  contracts/KVStore.sol 
2018-10-01 10:21:28,865: [11912] m.main:INFO: Beginning analysis
2018-10-01 10:21:28,866: [11912] m.ethereum:INFO: Starting symbolic create contract
2018-10-01 10:21:29,349: [11912] m.ethereum:INFO: Starting symbolic transaction: 0
2018-10-01 10:29:12,346: [11912] m.c.s.solver:WARNING: Found an unknown core, probably a solver timeout
(error "out of memory")
2018-10-01 10:33:07,622: [11912] m.c.executor:ERROR: Exception: 
Traceback (most recent call last):
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/core/executor.py", line 475, in run
    current_state = self.fork(current_state, e.expression, e.policy, e.setstate)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/core/executor.py", line 382, in fork
    solutions = state.concretize(expression, policy)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/core/state.py", line 279, in concretize
    m, M = self._solver.minmax(self._constraints, symbolic)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/core/smtlib/solver.py", line 107, in minmax
    m = self.min(constraints, x, iters)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/core/smtlib/solver.py", line 102, in min
    return self.optimize(constraints, X, 'minimize')
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/core/smtlib/solver.py", line 436, in optimize
    while self._check() == 'sat':
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/core/smtlib/solver.py", line 279, in _check
    raise SolverException(_status)
SolverException

Traceback (most recent call last):
  File "/home/posix4e/.local/bin/manticore", line 11, in <module>
    load_entry_point('manticore==0.1.10', 'console_scripts', 'manticore')()
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/__main__.py", line 149, in main
    ethereum_cli(args)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/__main__.py", line 135, in ethereum_cli
    m.multi_tx_analysis(args.argv[0], args.contract, args.txlimit, not args.txnocoverage, args.txaccount)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/ethereum.py", line 1735, in multi_tx_analysis
    value=symbolic_value)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/ethereum.py", line 1526, in transaction
    self._transaction('CALL', caller, value=value, address=address, data=data)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/ethereum.py", line 1694, in _transaction
    self.run(procs=self._config_procs)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/ethereum.py", line 1767, in run
    super(ManticoreEVM, self).run(**kwargs)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/manticore.py", line 638, in run
    self._start_workers(procs, profiling=should_profile)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/manticore.py", line 419, in _start_workers
    target()
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/core/executor.py", line 503, in run
    self._publish('will_terminate_state', current_state, current_state_id, e)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/utils/event.py", line 118, in _publish
    self._publish_impl(_name, *args, **kwargs)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/utils/event.py", line 126, in _publish_impl
    callback(robj(), *args, **kwargs)
  File "/home/posix4e/.local/lib/python2.7/site-packages/manticore/ethereum.py", line 1875, in _terminate_state_callback
    assert tx.result in {'SELFDESTRUCT', 'RETURN', 'STOP'}
AssertionError
posix4e@localhost:~/src
```

**Comment by posix4e** [comment]
surya has useless output

**Comment by posix4e** [comment]
/mnt/src/eth-kvstore # slither  contracts/KVStore.sol 
INFO:Slither:Compilation warnings/errors on contracts/KVStore.sol:
Warning: This is a pre-release compiler version, please do not use it in production.

INFO:Slither:contracts/KVStore.sol analyzed (1 contracts), 0 result(s) found
/mnt/src/eth-kvstore #

**Comment by posix4e** [comment]
```
/mnt/src/eth-kvstore # slither  contracts/KVStore.sol  --printer-summary --detect-backdoor --detect-unini
tialized-state --detect-pragma --detect-solc-version --detect-reentrancy --detect-reentrancy --detect-uni
nitialized-storage --detect-unused-state --detect-tx-origin
INFO:Slither:Compilation warnings/errors on contracts/KVStore.sol:
Warning: This is a pre-release compiler version, please do not use it in production.

INFO:Printers:
Contract KVStore
Contract vars: ['MAX_STRING_LENGTH', 'store']
Inheritance:: []
 
+----------+------------+-----------+-----------------------+-----------+-------------------+----------------+
| Function | Visibility | Modifiers |          Read         |   Write   |   Internal Calls  | External Calls |
+----------+------------+-----------+-----------------------+-----------+-------------------+----------------+
|   get    |   public   |     []    |       ['store']       |     []    |         []        |       []       |
|   set    |   public   |     []    | ['MAX_STRING_LENGTH'] | ['store'] | ['require(bool)'] |       []       |
+----------+------------+-----------+-----------------------+-----------+-------------------+----------------+

+-----------+------------+------+-------+----------------+----------------+
| Modifiers | Visibility | Read | Write | Internal Calls | External Calls |
+-----------+------------+------+-------+----------------+----------------+
+-----------+------------+------+-------+----------------+----------------+

INFO:Slither:contracts/KVStore.sol analyzed (1 contracts), 0 result(s) found

```

**Comment by posix4e** [comment]
@rbval also did some scans as well
